# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the circleci build base image here.    
      # note: can't use this gcloud image since it doesn't have maven and likely jdk8.  should create custom to combine the 2 images.
      #- image: google/cloud-sdk
      - image: circleci/openjdk:8-jdk
      
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - run: 
          name: Download Google App Engine SDK and make sure the components are up to date
          command: |
            curl -o ~/google-cloud-sdk.zip https://dl.google.com/dl/cloudsdk/channels/rapid/google-cloud-sdk.zip
            unzip -q -d ~/ ~/google-cloud-sdk.zip
            rm ~/google-cloud-sdk.zip
            #update components
            ~/google-cloud-sdk/bin/gcloud --quiet components list
            ~/google-cloud-sdk/bin/gcloud --quiet components update            
            # Retrieve our gcloud service account from the CircleCI environment
            echo $GOOGLE_AUTH | base64 --decode --ignore-garbage > ~/gcp-key.json
            ~/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file  ~/gcp-key.json      
            # Set the gcloud config environment like current project
            ~/google-cloud-sdk/bin/gcloud --quiet config set project $GOOGLE_PROJECT_ID     
            # don't need right now.
            #gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            #gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}
                
      # Get the code    
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      # Build
      #- run: mvn -DskipTests=true appengine:stage
      
      # run tests!
      #- run: mvn integration-test
      