# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
defaults: &defaults
    working_directory: ~/workspace
    docker:
      # Specify the build base image here.    
      - image: mmosttler/circleci_openjdk_gcloud:8u151-jdk-gcloud-182      

jobs:
  build:
    <<: *defaults
    environment:      
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m    
     # Get the code    
    steps:            
      - checkout

      - run: 
          name: Setup Google App Engine SDK
          command: |
            # retrieve our gcloud service account from the CircleCI environment
            echo $GOOGLE_AUTH | base64 --decode --ignore-garbage > ~/gcp-key.json
            gcloud auth activate-service-account --key-file  ~/gcp-key.json      
            # set the gcloud config environment like current project
            gcloud --quiet config set project $GOOGLE_PROJECT_PREFIX-dev1
            # don't need right now.
            #gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            #gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}  
            
            comp=$(echo "$CIRCLE_REPOSITORY_URL" | sed 's/./\L&/g' | sed 's/[\.\+]/-/g')
            echo $comp
            
            echo "export TEST=$(echo "$CIRCLE_REPOSITORY_URL" | sed 's/./\L&/g' | sed 's/[\.\+]/-/g')" >> $BASH_ENV
            echo $TEST
            echo $CIRCLE_REPOSITORY_URL | sed 's/./\L&/g' | sed 's/[\.\+]/-/g'
            
                      
      - save_cache:
          key: v1-gcloud-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/.config/gcloud

      # Download and cache application dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          key: v1-dependencies-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2 

      - run: mvn appengine:stage

      - persist_to_workspace:
          root: ~/workspace
          paths:
            - pom.xml
            - .springBeans
            - src/*
            - target/*
      
  unit-test:
    <<: *defaults
    steps:        
      - attach-workspace:
          at: ~/workspace
      - restore_cache:
          key: v1-dependencies-{{ checksum "pom.xml" }}
  
      - run:
          name: Run Unit Tests
          command: mvn test -DskipTests=false
      - run:
          name: Save test results 
          command: |
            mkdir -p ~/junit/ 
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit         
  
  integration-test:
    <<: *defaults
    steps:        
      - attach-workspace:
          at: ~/workspace
      - restore_cache:
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - restore_cache:
          key: v1-gcloud-{{ .Environment.CIRCLE_SHA1 }}
  
      - run:
          name: Start DataStore
          command: gcloud beta emulators datastore start
          background: true
      - run:
          name: Run Integration Tests
          command: mvn verify
      - run:
          name: Save test results 
          command: |
            mkdir -p ~/junit/ 
            find . -type f -regex ".*/target/failsafe-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit         

  deploy-dev:  
    <<: *defaults
    steps:        
      - attach-workspace:
          at: ~/workspace
      - restore_cache:
          key: v1-gcloud-{{ .Environment.CIRCLE_SHA1 }}
      - deploy: 
          name: Deploy to DEV
          command: gcloud app deploy target/appengine-staging/app.yaml --version v$CIRCLE_TAG-$CIRCLE_BUILD_NUM
      - store_artifacts:
          path: ~/.config/gcloud/logs 
      
  deploy-uat:  
    <<: *defaults
    steps:        
      - attach-workspace:
          at: ~/workspace
      - deploy: 
          name: Deploy to UAT
          command: |
            # retrieve our gcloud service account from the CircleCI environment
            echo $GOOGLE_AUTH_UAT1 | base64 --decode --ignore-garbage > ~/gcp-key.json
            gcloud auth activate-service-account --key-file  ~/gcp-key.json      
            # set the gcloud config environment like current project
            gcloud --quiet config set project $GOOGLE_PROJECT_PREFIX-uat1
            # don't need right now.
            #gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            #gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}            
  
            #deploy        
            echo "export TEST='HELLO.new+world' | sed 's/./\L&/g' | sed 's/[\.\+]/-/g'" >> $BASH_ENV
            echo $TEST
            echo $CIRCLE_TAG | sed 's/./\L&/g' | sed 's/[\.\+]/-/g'
            gcloud app deploy target/appengine-staging/app.yaml --no-promote --no-stop-previous-version --version v$CIRCLE_TAG-$CIRCLE_BUILD_NUM

  deploy-loadtest:  
    <<: *defaults
    steps:        
      - attach-workspace:
          at: ~/workspace
      - restore_cache:
          key: v1-gcloud-{{ .Environment.CIRCLE_SHA1 }}
      - deploy: 
          name: Deploy to LOAD TEST
          command: gcloud app deploy target/appengine-staging/app.yaml --no-promote --no-stop-previous-version --version v$CIRCLE_TAG-$CIRCLE_BUILD_NUM
            
  deploy-prod:  
    <<: *defaults
    steps:        
      - attach-workspace:
          at: ~/workspace
      - restore_cache:
          key: v1-gcloud-{{ .Environment.CIRCLE_SHA1 }}
      - deploy: 
          name: Deploy to PROD
          command: gcloud app deploy target/appengine-staging/app.yaml --no-promote --no-stop-previous-version --version v$CIRCLE_TAG-$CIRCLE_BUILD_NUM

# git ls-remote |grep $(git ls-remote | grep HEAD | grep -o '^[0-9a-zA-Z]*')|grep -o '[0-9]\.[0-9]\..*'
# ^(\d+\.\d+\.\d+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?[\^\{\}]*$
workflows:
  version: 2
  build-deploy-promote:
    jobs:    
      - build:
          filters:
            tags:
              only: /.*/
      - unit-test:
          filters:
            tags:
              only: /.*/
          requires:
            - build
      - integration-test:
          filters:
            tags:
              only: /.*/
          requires:
            - build            

      - deploy-dev:
          filters:
            tags:
              only: /.*/
          requires:        
            - unit-test
            - integration-test
            
      - deploy-uat:      
          filters:
            tags:
              only: /^(\d+\.\d+\.\d+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+(uat))?[\^\{\}]*$/
            branches:
              ignore: /.*/
          requires:        
            - unit-test
            - integration-test

      - deploy-loadtest:      
          filters:
            tags:
              only: /loadtest/
            branches:
              ignore: /.*/
          requires:        
            - unit-test
            - integration-test

      - hold-prod:
          type: approval
          filters:
            tags:
              only: /prod/
            branches:
              ignore: /.*/
          requires:
            - unit-test
            - integration-test
      - deploy-prod:
          filters:
            tags:
              only: /prod/
            branches:
              ignore: /.*/
          requires:        
            - hold-prod
      